{% set name = "gwdetchar" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8991da302a100a4a0ea6a2c1c29a3779c2ceaa24f48fbd23d7833d250e8b225a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - gwdetchar-conlog = gwdetchar.conlog:main
    - gwdetchar-lasso-correlation = gwdetchar.lasso.__main__:main
    - gwdetchar-mct = gwdetchar.mct:main
    - gwdetchar-nagios = gwdetchar.nagios.__main__:main
    - gwdetchar-omega = gwdetchar.omega.__main__:main
    - gwdetchar-omega-batch = gwdetchar.omega.batch:main
    - gwdetchar-overflow = gwdetchar.overflow:main
    - gwdetchar-scattering = gwdetchar.scattering.__main__:main
    - gwdetchar-scattering-simple = gwdetchar.scattering.simple:main
    - gwdetchar-slow-correlation = gwdetchar.lasso.old:main
    - gwdetchar-software-saturations = gwdetchar.saturation.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - astropy-base >=3.0.0
    - beautifulsoup4
    - coloredlogs
    - gwdatafind
    - gwpy >=3.0.10
    - gwtrigfind
    - lalsuite
    - lxml
    - markuppy >=1.14
    - matplotlib-base >=3.9
    - numpy >=1.16
    - pandas
    - pycondor
    - python >={{ python_min }}
    - pygments >=2.7.3
    - python-ligo-lw
    - pytz
    - python-ldas-tools-framecpp
    - scikit-learn
    - scipy >=1.2.0

test:
  requires:
    - flake8
    - pip
    - pytest >=3.3.0
    - pytest-cov >=2.4.0
    - python {{ python_min }}
  imports:
    - gwdetchar
    - gwdetchar.cds
    - gwdetchar.cli
    - gwdetchar.condor
    - gwdetchar.const
    - gwdetchar.daq
    - gwdetchar.io
    - gwdetchar.io.html
    - gwdetchar.io.datafind
    - gwdetchar.lasso
    - gwdetchar.lasso.plot
    - gwdetchar.nagios
    - gwdetchar.plot
    - gwdetchar.omega
    - gwdetchar.omega.plot
    - gwdetchar.omega.html
    - gwdetchar.omega.config
    - gwdetchar.saturation
    - gwdetchar.scattering
    - gwdetchar.scattering.plot
    - gwdetchar.utils
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show gwdetchar
    # run unit tests
    - python -m pytest --verbose --pyargs {{ name }}
    # check scripts run ok
    - python -m gwdetchar.conlog --help
    - python -m gwdetchar.lasso --help
    - python -m gwdetchar.lasso.old --help
    - python -m gwdetchar.mct --help
    - python -m gwdetchar.nagios --help
    - python -m gwdetchar.omega --help
    - python -m gwdetchar.omega.batch --help
    - python -m gwdetchar.overflow --help
    - python -m gwdetchar.saturation --help
    - python -m gwdetchar.scattering --help
    - python -m gwdetchar.scattering.simple --help

about:
  home: https://gwdetchar.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave detector characterisation
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - eagoetz
    - areeda
    - robertbruntz
