{% set name = "gwdetchar" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0fc90969cdcd56a9ffdea3400034caab58795685682387040f33583cc5efc55e
  patches:
    # fix test failures on python3.8
    - 0001-gwdetchar.conftest-add-pytest-fixture-overrides.patch

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py<35]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - astropy >=1.2
    - beautifulsoup4
    - gwdatafind
    - gwpy >=0.13.0
    - gwtrigfind
    - lxml
    - markuppy >=1.14
    - matplotlib-base >=2.0.0
    - numpy >=1.16
    - pandas
    - pathlib2  # [py<36]
    - pycondor
    - python
    - pytz
    - coloredlogs
    - pygments
    - python-ldas-tools-framecpp
    - scikit-learn
    - scipy >=1.2.0
    - setuptools

test:
  requires:
    - flake8
    - pytest
    - coverage
  imports:
    - gwdetchar
    - gwdetchar.cds
    - gwdetchar.cli
    - gwdetchar.condor
    - gwdetchar.const
    - gwdetchar.daq
    - gwdetchar.io
    - gwdetchar.io.html
    - gwdetchar.io.datafind
    - gwdetchar.io.tests
    - gwdetchar.lasso
    - gwdetchar.lasso.plot
    - gwdetchar.lasso.tests
    - gwdetchar.plot
    - gwdetchar.omega
    - gwdetchar.omega.plot
    - gwdetchar.omega.html
    - gwdetchar.omega.config
    - gwdetchar.omega.tests
    - gwdetchar.saturation
    - gwdetchar.scattering
    - gwdetchar.scattering.plot
    - gwdetchar.scattering.tests
    - gwdetchar.tests
    - gwdetchar.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check scripts run ok
    - gwdetchar-lasso-correlation --help
    - gwdetchar-mct --help
    - gwdetchar-omega --help
    - gwdetchar-omega-batch --help
    - gwdetchar-overflow --help
    - gwdetchar-scattering --help
    - python -m gwdetchar.scattering --help
    - gwdetchar-slow-correlation --help
    - gwdetchar-software-saturations --help
    - python -m gwdetchar.nagios --help

about:
  home: "https://gwdetchar.readthedocs.io"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: "A python package for gravitational-wave detector characterisation"
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
