{% set name = "gwdetchar" %}
{% set version = "2.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc188b1bd9ac79acbb311eacc6f70f2b8aea043539130fc909630fc628275c58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - gwdetchar-conlog = gwdetchar.conlog:main
    - gwdetchar-lasso-correlation = gwdetchar.lasso.__main__:main
    - gwdetchar-mct = gwdetchar.mct:main
    - gwdetchar-nagios = gwdetchar.nagios.__main__:main
    - gwdetchar-omega = gwdetchar.omega.__main__:main
    - gwdetchar-omega-batch = gwdetchar.omega.batch:main
    - gwdetchar-overflow = gwdetchar.overflow:main
    - gwdetchar-scattering = gwdetchar.scattering.__main__:main
    - gwdetchar-scattering-simple = gwdetchar.scattering.simple:main
    - gwdetchar-slow-correlation = gwdetchar.lasso.old:main
    - gwdetchar-software-saturations = gwdetchar.saturation.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=20.2.2
  run:
    - astropy >=3.0.0
    - beautifulsoup4
    - coloredlogs
    - gwdatafind
    - gwpy >=2.0.0
    - gwtrigfind
    - lalsuite
    - lscsoft-glue >=2.0.0
    - lxml
    - markuppy >=1.14
    - matplotlib-base >=3.1.0
    - numpy >=1.16
    - pandas
    - pycondor
    - python >=3.6
    - pygments >=2.7.3
    - pytz
    - python-ldas-tools-framecpp
    - scikit-learn
    - scipy >=1.2.0

test:
  requires:
    - flake8
    - pytest >=3.3.0
    - pytest-cov >2.4.0
  imports:
    - gwdetchar
    - gwdetchar.cds
    - gwdetchar.cli
    - gwdetchar.condor
    - gwdetchar.const
    - gwdetchar.daq
    - gwdetchar.io
    - gwdetchar.io.html
    - gwdetchar.io.datafind
    - gwdetchar.lasso
    - gwdetchar.lasso.plot
    - gwdetchar.nagios
    - gwdetchar.plot
    - gwdetchar.omega
    - gwdetchar.omega.plot
    - gwdetchar.omega.html
    - gwdetchar.omega.config
    - gwdetchar.saturation
    - gwdetchar.scattering
    - gwdetchar.scattering.plot
    - gwdetchar.utils
  commands:
    # run unit tests
    - python -m pytest --verbose --pyargs {{ name }}
    # check scripts run ok
    - python -m gwdetchar.conlog --help
    - python -m gwdetchar.lasso --help
    - python -m gwdetchar.lasso.old --help
    - python -m gwdetchar.mct --help
    - python -m gwdetchar.nagios --help
    - python -m gwdetchar.omega --help
    - python -m gwdetchar.omega.batch --help
    - python -m gwdetchar.overflow --help
    - python -m gwdetchar.saturation --help
    - python -m gwdetchar.scattering --help
    - python -m gwdetchar.scattering.simple --help

about:
  home: https://gwdetchar.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave detector characterisation
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - eagoetz
    - areeda
    - robertbruntz
